---
- name: Update APT cache
  apt: update_cache=yes

- name: Install os packages
  apt: pkg="{{ item }}" state=present
  with_items:
    - ntp

- name: Install OpenJDK
  apt: pkg="{{ item }}" state=present
  when: java == "openjdk"
  with_items:
    - openjdk-8-jre
    - openjfx


