---
- name: start corda
  systemd: daemon_reload=yes name=corda enabled=yes state=started

- name: restart corda
  systemd: daemon_reload=yes name=corda enabled=yes state=restarted

- name: start corda-webserver
  systemd: daemon_reload=yes name=corda-webserver enabled=yes state=started

- name: restart corda-webserver
  systemd: daemon_reload=yes name=corda-webserver enabled=yes state=restarted

